### ISSUE TITLE
在线播放

### ISSUE THREAD

**Issue by MoeShadows** [a188037445/file-sharer#1]
请问可以添加一个在线播放吗,复制到mxplayer再播放不方便,感谢大佬

**Comment by a188037445** [comment]
可以，我研究下。

**Comment by MoeShadows** [comment]
大佬,可以参考一下这个,https://pan.baidu.com/s/15sSHgP48Il4rOXME4qA1hw

**Comment by MoeShadows** [comment]
搞错了抱歉,还是您的简洁好用,如果有播放功能就完美了

**Comment by MoeShadows** [comment]
在电脑端直接访问貌似会出错
![QQ截图20200331122433](https://user-images.githubusercontent.com/38324038/77986846-bd5d3d80-734a-11ea-8930-b0785308355a.png)

**Comment by a188037445** [comment]
> 在电脑端直接访问貌似会出错
> ![QQ截图20200331122433](https://user-images.githubusercontent.com/38324038/77986846-bd5d3d80-734a-11ea-8930-b0785308355a.png)

命令提示符下输入 echo %USERPROFILE% 然后回车，把结果贴上来。我这是可以访问的。

**Comment by MoeShadows** [comment]
我的用户目录在e盘
![QQ截图20200331124145](https://user-images.githubusercontent.com/38324038/77987743-39588500-734d-11ea-91ff-f491e366de2d.png)

**Comment by MoeShadows** [comment]
关于对文件的下载(图片的查看)似乎名称有些错误

**Comment by MoeShadows** [comment]
![Screenshot_2020-03-31-12-44-34](https://user-images.githubusercontent.com/38324038/77987943-ba178100-734d-11ea-8401-5cf74961012a.png)

**Comment by MoeShadows** [comment]
![Screenshot_2020-03-31-12-39-01](https://user-images.githubusercontent.com/38324038/77987991-d2879b80-734d-11ea-9936-5640ace47030.png)

**Comment by a188037445** [comment]
你是不是目录指定错了？

**Comment by a188037445** [comment]
图片文件名的问题，应该是浏览器的bug。

**Comment by MoeShadows** [comment]
我用别的程序可以...

**Comment by MoeShadows** [comment]
手机端看得到网页

**Comment by a188037445** [comment]
那我就不清楚了，需要提供更多信息才能判断是什么问题。

**Comment by MoeShadows** [comment]
那么请问大佬,在线播放有头绪了吗

**Comment by a188037445** [comment]
> 那么请问大佬,在线播放有头绪了吗

[https://github.com/a188037445/file-sharer/releases/tag/1.0.3](url)

**Comment by MoeShadows** [comment]
好嘞

**Comment by MoeShadows** [comment]
请问手机Android上什么浏览器可以在线放啊,我用夸克好像只能下载

**Comment by a188037445** [comment]
> 请问手机Android上什么浏览器可以在线放啊,我用夸克好像只能下载

换个浏览器试试呢？
