### ISSUE TITLE
新bug?

### ISSUE THREAD

**Issue by MoeShadows** [a188037445/file-sharer#2]
![QQ截图20200331144445](https://user-images.githubusercontent.com/38324038/77995351-374af200-735e-11ea-8176-af47428da22c.png)

**Comment by a188037445** [comment]
同一个地址和端口不能重复使用，如果你已经打开了一个相同端口的服务器程序，就先关闭它。

**Comment by MoeShadows** [comment]
抱歉忘记关了

**Comment by MoeShadows** [comment]
建议给一个提醒,一闪而过我真的以为是错误

**Comment by a188037445** [comment]
按照国际惯例，错误都是输出到控制台的。而且如果我加了提醒，在终端里运行的时候就需要多操作一步才能关闭了。
